terminal:
	docker compose exec -u root processor bash

deps:
	poetry install

start:
	poetry run processor

up:
	docker compose up

clean:
	docker compose down --volumes

build:
	docker compose build

